version: '3.9'

services:
  payments:
    build:
      context: .
      target: dev
    entrypoint: [ "air", "-d" ]
    links:
      - payments-db
    environment:
      - 'POSTGRES_HOST=payments-db'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DATABASE=${POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'PROJ_NAME=${PROJ_NAME}'
      - 'PROJ_ENV=${PROJ_ENV}'
    ports:
      - '8080:8080'
      - '2345:2345'
    volumes:
      - .:/usr/github.com/isaias-dgr/ecommerce_services

  payments-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DATABASE=${POSTGRES_DATABASE}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    restart: unless-stopped
    volumes:
      - ./datadb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80

    depends_on:
      - payments-db
