-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
CREATE TABLE ShoppingCarts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CartID UUID UNIQUE,
    OwnerID UUID NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ShoppingCartItems (
    ItemID UUID ,
    CartID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    FOREIGN KEY (CartID) REFERENCES ShoppingCarts(id) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
