-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
CREATE TABLE AcquiringBanks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BankID UUID UNIQUE,
    Name VARCHAR(255) NOT NULL,
    BankCode VARCHAR(255) NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
