-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
CREATE TABLE Customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID UUID UNIQUE,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PaymentMethodID INT
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
