-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
CREATE TABLE PaymentMethods (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PaymentMethodID UUID UNIQUE,
    CardNumber BYTEA NOT NULL,
    ExpirationDate DATE NOT NULL,
    CVV BYTEA NOT NULL,
    CardholderName VARCHAR(255) NOT NULL,
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES Customers(ID)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
