-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
CREATE TABLE BankAccounts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountInfoID UUID UNIQUE,
    AccountNumber BYTEA NOT NULL,
    BankName VARCHAR(255) NOT NULL,
    BranchCode VARCHAR(255) NOT NULL,
    MerchantID int,
    FOREIGN KEY (MerchantID) REFERENCES Merchants(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
